### ISSUE TITLE
mvnc creates non-working config

### ISSUE THREAD

**Issue by jvalkeal** [jfrog/jfrog-cli#536]
CLI version `1.32.2` and Artifactory Trial `6.16.0 rev 61600900`

When running:
```
jfrog rt mvnc
```
resulting config is for example:
```
type: maven
deployer:
  snapshotRepo: libs-snapshot
  releaseRepo: libs-release
```
Then `mvn` command `jfrog rt mvn "clean install -Dartifactory.publish.buildInfo=true"` fails:
```
[main] ERROR org.jfrog.build.extractor.maven.BuildInfoRecorder - org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded() listener has failed: 
java.lang.IllegalArgumentException: Unable to resolve Artifactory Build Info Client properties: no context URL was found.
    at org.jfrog.build.extractor.maven.BuildInfoClientBuilder.resolveClientProps (BuildInfoClientBuilder.java:36)
    at org.jfrog.build.extractor.maven.BuildInfoClientBuilder.resolveProperties (BuildInfoClientBuilder.java:26)
    at org.jfrog.build.extractor.maven.BuildDeploymentHelper.deployArtifacts (BuildDeploymentHelper.java:298)
```
You need to manually add undocumented options like:
```
version: 1
type: maven
deployer:
  snapshotRepo: libs-snapshot
  releaseRepo: libs-release
  url: http://localhost:8081/artifactory
  username: admin
  password: APLU2Fd9kTNSnyDYmbJ4Vuy7A1
```

**Comment by Or-Gabay** [comment]
@jvalkeal,
Thanks for reporting this.
We released JFrog CLI v1.32.3 to resolve this issue.
Feel free to upgrade - We'll appreciate your feedback for that!

**Comment by jvalkeal** [comment]
Right thanks, works now and I don't need to have those extras in a config!

**Comment by Arun1111** [comment]
@Or-Gabay 

I am using the latest version 1.32.4 and still facing the issue could you please suggest. 

Thanks

**Comment by Or-Gabay** [comment]
Duplicate - https://github.com/jfrog/jfrog-cli/issues/554
