### ISSUE TITLE
Could not find docker image in Artifactory, expecting image ID when pulling from remote

### ISSUE THREAD

**Issue by trriplejay** [jfrog/jfrog-cli#674]
**Describe the bug**
When pulling a library image from an Artifactory remote docker repository that points to docker hub, I receive the following error:
```
jfrog rt docker-pull <ip>/docker-remote/mariadb:10.2.23 docker-remote --build-name=mariadbtest --build-number=1
10.2.23: Pulling from docker-remote/mariadb
Digest: sha256:af57a388784d08cd2d4f054fabfc53aa9144a961a3a1be8067a5cf9443d01646
Status: Image is up to date for <ip>/docker-remote/mariadb:10.2.23
<ip>/docker-remote/mariadb:10.2.23
[Error] Could not find docker image in Artifactory, expecting image ID: sha256:de1cba14a3a39248a24bbc1ea1c981a53c56ab0d374299d691736cd84aedc217
```
I notice that if I do not include the --build-name and --build-number parameters, the pull works as expected.  

I thought that this error could be due to the build name/number not yet existing in Artifactory, but according to the CLI documentation, those parameters are just used to gather data locally so that a build can later be published.

**To Reproduce**
set up a remote docker repository that points to `https://registry-1.docker.io/`
configure the jfrog CLI and issue jfrog rt docker-pull of some library image through the docker-remote repo, specifying the --build-name and --build-number parameters.
```
jfrog rt docker-pull <ip>/docker-remote/mariadb:10.2.23 docker-remote --build-name=mariadbtest --build-number=1
```

**Expected behavior**
I'd expect the image to pull successfully, regardless of whether or not i provide the --build-name and --build-number parameters

**Versions**
- JFrog CLI version: 1.35.3
- JFrog CLI operating system: ubuntu 18.04
- Artifactory Version: 7.3

**Comment by Or-Gabay** [comment]
@trriplejay, We truly apologize for this incident, while we investigate this issue I would like to help you with a workaround until this gets patched.
Create a virtual docker repository add your remote docker repository to it (the one that points to docker hub).
Now try to pull from your virtual docker repository with build-name & build-number flags.

**Comment by Or-Gabay** [comment]
@trriplejay, we released JFrog CLI v1.35.4 to resolve this issue.
Feel free to upgrade - We'll appreciate your feedback for that!

**Comment by whume** [comment]
We just ran into this on the azure devops extension and got around it by disabling collection of build info but the issue still seems present in cCLI version v1.35.5

**Comment by dragoonTND** [comment]
To add to @whume, this was seen on a docker push rather than a pull for us

**Comment by dragoonTND** [comment]
> We just ran into this on the azure devops extension and got around it by disabling collection of build info but the issue still seems present in cCLI version v1.35.5

To add to @whume. We say this on a push rather than a pull

**Comment by eyalbe4** [comment]
@whume and @dragoonTND,
Could it be that you're providing to the command a different repository, than the repository the reverse proxy is pointed to?
If this is not the issue, can you please help us reproduce the issue? If you can create step by step instructions, that could be extremely helpful. 
 Everything works for us with the latest release.

**Comment by trriplejay** [comment]
This is working for my case now 👍 thanks!

**Comment by eyalbe4** [comment]
Thanks for the feedback @trriplejay.

@whume and @dragoonTND, did you see my comment above?

**Comment by whume** [comment]
Ah I missed this let me give it a try when im online in the morning and ill try enabling build info again.
